#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
#20200602 - Created script to remotely backup Files
#         - Stops all Usenet and Torrent services to prevent downloading through VPN
#20200614 - Added confirmation that disks are mounted and logging file
#
echo "-----------------------------------------"
echo "--[ Stopping All Downloading Services ]--"
echo "-----------------------------------------"
sudo systemctl stop deluged sabnzbd nzbdrone radarr nzbhydra
echo "-------------------------------"
echo "--[ Connecting to WireGuard ]--"
echo "-------------------------------"
sudo wg-quick up wg0
sudo wg
echo "------------------------"
echo "--[ Mounting NNVault ]--"
echo "------------------------"
sudo mount -t cifs //10.0.100.10/Files /nnvault/Files -o credentials=/home/nn/.smbnnvault
echo "---------------------------------------------------"
echo "--[ Confirming Backup Disk and CIFS are mounted ]--"
echo "---------------------------------------------------"
if grep -qs '/mnt/backup ' /proc/mounts; then
  echo "Backup Disk Mounted"
  if grep -qs '/nnvault/Files ' /proc/mounts; then
    echo "NNVault Files CIFS Mounted"
    echo "--------------------------------"
    echo "--[ Run Dry-Run Rsync? (y/n) ]--"
    echo "--------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
      sudo rsync -anzh --inplace --info=progress2 --delete-during --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/ /mnt/backup/NNVault/Files/ --log-file=/mnt/backup/logs/remote_backup_"$(date +%Y-%m-%d_%H%M%S)".log
    fi
    echo "-----------------------------"
    echo "--[ Run Real Rsync? (y/n) ]--"
    echo "-----------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
      sudo rsync -azh --inplace --info=progress2 --delete-during --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/ /mnt/backup/NNVault/Files/ --log-file=/mnt/backup/logs/remote_backup_"$(date +%Y-%m-%d_%H%M%S)".log
    fi
  else
    echo "Error : NNVault Files CIFS Unmounted"
  fi
else
  echo "Error : Backup Disk Unmounted"
fi
#Cleanup
sudo umount -t cifs //10.0.100.10/Files
sudo wg-quick down wg0
sudo systemctl start deluged sabnzbd nzbdrone radarr nzbhydra