#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
#20200608 - Created to transfer bookstack files to nnpi
#
systemctl stop deluged sabnzbd nzbdrone radarr nzbhydra
wg-quick up wg0
mount -t cifs //10.0.100.10/Backup /nnvault/Backup -o credentials=/home/nn/.smbnnvault
mount -t cifs //192.168.5.41/bookstack /bookstack -o credentials=/home/nn/.smbnnpi
if grep -qs '/nnvault/Backup ' /proc/mounts; then
  if grep -qs '/bookstack ' /proc/mounts; then
  sudo cp $(ls -t /nnvault/Backup/NNServer/WEB.BookStack/Backup/* | head -1) /bookstack
  else
    echo "Error : NNPi Unmounted"
  fi
else
  echo "Error : NNVault Unmounted"
fi
#Cleanup
umount -t cifs //192.168.5.41/bookstack
umount -t cifs //10.0.100.10/Backup
wg-quick down wg0
systemctl start deluged sabnzbd nzbdrone radarr nzbhydra