#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
#20200602 - Created script for cron to remotely backup Files
#
systemctl stop deluged sabnzbd nzbdrone radarr nzbhydra
wg-quick up wg0
mount -t cifs //10.0.100.10/files /vault/Files -o credentials=/home/nn/.smbvault
rsync -azh --inplace --info=progress2 --delete-during --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /vault/Files/ /mnt/backup/Files/
#Cleanup
umount -t cifs /10.0.100.10/files
wg-quick down wg0
systemctl start deluged sabnzbd nzbdrone radarr nzbhydra